"""empty message

Revision ID: 035097588c00
Revises: 
Create Date: 2021-10-15 13:10:59.305066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035097588c00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('last_name', sa.String(length=10), nullable=True),
    sa.Column('user_name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('favorito_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=125), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'url', name='unico_favorito_para_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorito_usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
